package com.trenddz;
import android.content.*; import android.net.Uri; import android.os.Bundle; import android.widget.*; import androidx.appcompat.app.AppCompatActivity; import org.json.*;
public class MainActivity extends AppCompatActivity {
 EditText url,name,price,image; Spinner provider; TextView output; JSONArray products;
 String[] providers={"Sawa9ly — PRODUCT → FORM","Baba Algeria — PRODUCT → FORM","DropDZ — PRODUCT أو FORM","Prix Choc — LANDING → FORM"};
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main); provider=findViewById(R.id.providerSpinner);url=findViewById(R.id.productUrl);name=findViewById(R.id.productName);price=findViewById(R.id.productPrice);image=findViewById(R.id.productImage);output=findViewById(R.id.output);provider.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,providers));products=load();findViewById(R.id.saveButton).setOnClickListener(v->save());findViewById(R.id.openButton).setOnClickListener(v->open());findViewById(R.id.exportButton).setOnClickListener(v->output.setText(export()));}
 void save(){try{JSONObject p=new JSONObject();p.put("provider",provider.getSelectedItem().toString());p.put("url",url.getText().toString().trim());p.put("name",name.getText().toString().trim());p.put("price",price.getText().toString().trim());p.put("image",image.getText().toString().trim());products.put(p);getPreferences(0).edit().putString("products",products.toString()).apply();output.setText("تم حفظ المنتج رقم "+products.length()+" ✓");}catch(Exception e){output.setText(e.toString());}}
 void open(){String u=url.getText().toString().trim();if(!u.isEmpty())startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(u)));}
 JSONArray load(){try{return new JSONArray(getPreferences(0).getString("products","[]"));}catch(Exception e){return new JSONArray();}}
 String export(){StringBuilder s=new StringBuilder("const storeData = {\n");for(int i=0;i<products.length();i++)try{JSONObject p=products.getJSONObject(i);s.append("  \\\""+(i+1)+"\\\": { provider: ").append(JSONObject.quote(p.optString("provider"))).append(", url: ").append(JSONObject.quote(p.optString("url"))).append(", name: ").append(JSONObject.quote(p.optString("name"))).append(", price: ").append(p.optString("price","0")).append(", image: ").append(JSONObject.quote(p.optString("image"))).append(" },\n");}catch(Exception e){}return s.append("};").toString();}
}
